name = "Dark Simplicity"
license = "MIT"
licenselink = "https://github.com/kritoke/darksimplicity/blob/master/LICENSE.txt"
description = "A Dark Minimalist Theme for Hugo utilizing the Lost Grid Framework."
homepage = "http://github.com/kritoke/darksimplicity"
tags = ["blog", "dark", "minimalist"]
features = ["blog"]
min_version = 0.18

[author]
    name = "Matt Rhone"
    homepage = "http://matthewrhone.com"